<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://iec.ch/TC57/2015/ReceiveWorkRequests" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:infoMessage="http://iec.ch/TC57/2015/WorkRequestsMessage" name="ReceiveWorkRequests" targetNamespace="http://iec.ch/TC57/2015/ReceiveWorkRequests">
	<wsdl:types>
		<xs:schema targetNamespace="http://iec.ch/TC57/2015/ReceiveWorkRequests" elementFormDefault="qualified">
			<xs:import namespace="http://iec.ch/TC57/2015/WorkRequestsMessage" schemaLocation="xsd/WorkRequestsMessage.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="CreatedWorkRequestsEventMessage">
		<wsdl:part name="CreatedWorkRequestsEventMessage" element="infoMessage:CreatedWorkRequests"/>
	</wsdl:message>
	<wsdl:message name="ResponseMessage">
		<wsdl:part name="ResponseMessage" element="infoMessage:WorkRequestsResponseMessage"/>
	</wsdl:message>
	<wsdl:message name="FaultMessage">
		<wsdl:part name="FaultMessage" element="infoMessage:WorkRequestsFaultMessage"/>
	</wsdl:message>
	<wsdl:portType name="WorkRequests_Port">
		<wsdl:operation name="CreatedWorkRequests">
			<wsdl:input name="CreatedWorkRequestsEvent" message="tns:CreatedWorkRequestsEventMessage"/>
			<wsdl:output name="CreatedWorkRequestsResponse" message="tns:ResponseMessage"/>
			<wsdl:fault name="CreatedWorkRequestsFault" message="tns:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="WorkRequests_Binding" type="tns:WorkRequests_Port">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="CreatedWorkRequests">
			<soap:operation soapAction="http://iec.ch/TC57/2015/WorkRequests/CreatedWorkRequests" style="document"/>
			<wsdl:input name="CreatedWorkRequestsEvent">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="CreatedWorkRequestsResponse">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="CreatedWorkRequestsFault">
				<soap:fault name="CreatedWorkRequestsFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ReceiveWorkRequests">
		<wsdl:port name="WorkRequests_Port" binding="tns:WorkRequests_Binding">
			<soap:address location="http://iec.ch/TC57/2015/ReceiveWorkRequests"/>
		</wsdl:port>
	</wsdl:service>
	<!-- Message Definitions -->
	<!-- Port Definitions -->
</wsdl:definitions>
