package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddressPositionPoints generated by hbm2java
 */
@Entity
@Table(name = "address_position_points")
public class AddressPositionPoints implements java.io.Serializable {

	private Integer id;
	private Address address;
	private Integer sequence;
	private Integer xposition;
	private Integer yposition;
	private Integer zposition;

	public AddressPositionPoints() {
	}

	public AddressPositionPoints(Address address) {
		this.address = address;
	}

	public AddressPositionPoints(Address address, Integer sequence,
			Integer xposition, Integer yposition, Integer zposition) {
		this.address = address;
		this.sequence = sequence;
		this.xposition = xposition;
		this.yposition = yposition;
		this.zposition = zposition;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "address_id", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "sequence")
	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	@Column(name = "xposition")
	public Integer getXposition() {
		return this.xposition;
	}

	public void setXposition(Integer xposition) {
		this.xposition = xposition;
	}

	@Column(name = "yposition")
	public Integer getYposition() {
		return this.yposition;
	}

	public void setYposition(Integer yposition) {
		this.yposition = yposition;
	}

	@Column(name = "zposition")
	public Integer getZposition() {
		return this.zposition;
	}

	public void setZposition(Integer zposition) {
		this.zposition = zposition;
	}

}
