package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address")
public class Address implements java.io.Serializable {
	private static Constraint con = new Constraint(Address.class);
	private static org.apache.log4j.Logger log = Logger
			.getLogger(Attachment.class);

	private Integer id;
	private String sdAddress1;
	private String sdAddress2;
	private String sdBuildingName;
	private String sdCode;
	private String sdNumber;
	private String sdPrefix;
	private String sdSuffix;
	private String sdSuiteNumber;
	private String sdType;
	private int sdWithinTownLimitsFlag;
	private String tdCode;
	private String tdCountry;
	private String tdName;
	private String tdSection;
	private String tdStateProvince;
	private String directions;
	private String tdPobox;
	private String tdPostalCode;
	private String tdRegion;
	private String county;
	private String townshipName;
	private String subdivision;
	private String block;
	private String lot;
	private String timeZone;
	private String coordSystem;
	private Set<AddressDistricts> addressDistrictses = new HashSet<AddressDistricts>(
			0);
	private Set<AddressPositionPoints> addressPositionPointses = new HashSet<AddressPositionPoints>(
			0);
	private Set<Organization> organizations = new HashSet<Organization>(0);
	private Set<ContactpersonAddresses> contactpersonAddresseses = new HashSet<ContactpersonAddresses>(
			0);
	private Set<AddressHazards> addressHazardses = new HashSet<AddressHazards>(
			0);
	private Set<WorkOrder> addressWorkOrders = new HashSet<WorkOrder>(
			0);
	

	public Address() {
	}

	public Address(int sdWithinTownLimitsFlag) {
		this.sdWithinTownLimitsFlag = sdWithinTownLimitsFlag;
	}

	public Address(String sdAddress1, String sdAddress2, String sdBuildingName,
			String sdCode, String sdNumber, String sdPrefix, String sdSuffix,
			String sdSuiteNumber, String sdType, int sdWithinTownLimitsFlag,
			String tdCode, String tdCountry, String tdName, String tdSection,
			String tdStateProvince, String directions, String tdPobox,
			String tdPostalCode, String tdRegion, String county,
			String townshipName, String subdivision, String block, String lot,
			String timeZone, String coordSystem,
			Set<AddressDistricts> addressDistrictses,
			Set<AddressPositionPoints> addressPositionPointses,
			Set<Organization> organizations,
			Set<ContactpersonAddresses> contactpersonAddresseses,
			Set<AddressHazards> addressHazardses) {
		this.sdAddress1 = sdAddress1;
		this.sdAddress2 = sdAddress2;
		this.sdBuildingName = sdBuildingName;
		this.sdCode = sdCode;
		this.sdNumber = sdNumber;
		this.sdPrefix = sdPrefix;
		this.sdSuffix = sdSuffix;
		this.sdSuiteNumber = sdSuiteNumber;
		this.sdType = sdType;
		this.sdWithinTownLimitsFlag = sdWithinTownLimitsFlag;
		this.tdCode = tdCode;
		this.tdCountry = tdCountry;
		this.tdName = tdName;
		this.tdSection = tdSection;
		this.tdStateProvince = tdStateProvince;
		this.directions = directions;
		this.tdPobox = tdPobox;
		this.tdPostalCode = tdPostalCode;
		this.tdRegion = tdRegion;
		this.county = county;
		this.townshipName = townshipName;
		this.subdivision = subdivision;
		this.block = block;
		this.lot = lot;
		this.timeZone = timeZone;
		this.coordSystem = coordSystem;
		this.addressDistrictses = addressDistrictses;
		this.addressPositionPointses = addressPositionPointses;
		this.organizations = organizations;
		this.contactpersonAddresseses = contactpersonAddresseses;
		this.addressHazardses = addressHazardses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sd_address_1", length = 20)
	public String getSdAddress1() {
		return this.sdAddress1;
	}

	public void setSdAddress1(String sdAddress1) {
		con.check( "setSdAddress1", sdAddress1, true, 20);
		this.sdAddress1 = sdAddress1;
	}

	@Column(name = "sd_address_2", length = 20)
	public String getSdAddress2() {
		return this.sdAddress2;
	}

	public void setSdAddress2(String sdAddress2) {
		con.check( "setSdAddress2", sdAddress2, true, 20);
		this.sdAddress2 = sdAddress2;
	}

	@Column(name = "sd_building_name", length = 20)
	public String getSdBuildingName() {
		return this.sdBuildingName;
	}

	public void setSdBuildingName(String sdBuildingName) {
		con.check( "setSdBuildingName", sdBuildingName, true, 20);
		this.sdBuildingName = sdBuildingName;
	}

	@Column(name = "sd_code", length = 20)
	public String getSdCode() {
		return this.sdCode;
	}

	public void setSdCode(String sdCode) {
		con.check( "setSdCode", sdCode, true, 20);
		this.sdCode = sdCode;
	}

	@Column(name = "sd_number", length = 8)
	public String getSdNumber() {
		return this.sdNumber;
	}

	public void setSdNumber(String sdNumber) {
		con.check( "setSdNumber", sdNumber, true, 8);
		this.sdNumber = sdNumber;
	}

	@Column(name = "sd_prefix", length = 10)
	public String getSdPrefix() {
		return this.sdPrefix;
	}

	public void setSdPrefix(String sdPrefix) {
		con.check( "setSdPrefix", sdPrefix, true, 10);
		this.sdPrefix = sdPrefix;
	}

	@Column(name = "sd_suffix", length = 10)
	public String getSdSuffix() {
		return this.sdSuffix;
	}

	public void setSdSuffix(String sdSuffix) {
		con.check( "setSdSuffix", sdSuffix, true, 10);
		this.sdSuffix = sdSuffix;
	}

	@Column(name = "sd_suite_number", length = 10)
	public String getSdSuiteNumber() {
		return this.sdSuiteNumber;
	}

	public void setSdSuiteNumber(String sdSuiteNumber) {
		con.check( "setSdSuiteNumber", sdSuiteNumber, true, 10);
		this.sdSuiteNumber = sdSuiteNumber;
	}

	@Column(name = "sd_type", length = 10)
	public String getSdType() {
		return this.sdType;
	}

	public void setSdType(String sdType) {
		con.check( "setSdType", sdType, true, 10);
		this.sdType = sdType;
	}

	@Column(name = "sd_within_town_limits_flag", nullable = false)
	public int getSdWithinTownLimitsFlag() {
		return this.sdWithinTownLimitsFlag;
	}

	public void setSdWithinTownLimitsFlag(int sdWithinTownLimitsFlag) {
		log.debug("setSdWithinTownLimitsFlag : " + sdWithinTownLimitsFlag);
		this.sdWithinTownLimitsFlag = sdWithinTownLimitsFlag;
	}

	@Column(name = "td_code", length = 20)
	public String getTdCode() {
		return this.tdCode;
	}

	public void setTdCode(String tdCode) {
		con.check( "setTdCode", tdCode, true, 20);
		this.tdCode = tdCode;
	}

	@Column(name = "td_country", length = 20)
	public String getTdCountry() {
		return this.tdCountry;
	}

	public void setTdCountry(String tdCountry) {
		con.check( "setTdCountry", tdCountry, true, 20);
		this.tdCountry = tdCountry;
	}

	@Column(name = "td_name", length = 20)
	public String getTdName() {
		return this.tdName;
	}

	public void setTdName(String tdName) {
		con.check( "setTdName", tdName, true, 20);
		this.tdName = tdName;
	}

	@Column(name = "td_section", length = 3)
	public String getTdSection() {
		return this.tdSection;
	}

	public void setTdSection(String tdSection) {
		con.check( "setTdSection", tdSection, true, 3);
		this.tdSection = tdSection;
	}

	@Column(name = "td_state_province", length = 20)
	public String getTdStateProvince() {
		return this.tdStateProvince;
	}

	public void setTdStateProvince(String tdStateProvince) {
		con.check( "setTdStateProvince", tdStateProvince, true, 20);
		this.tdStateProvince = tdStateProvince;
	}

	@Column(name = "directions", length = 512)
	public String getDirections() {
		return this.directions;
	}

	public void setDirections(String directions) {
		con.check( "setDirections", directions, true, 512);
		this.directions = directions;
	}

	@Column(name = "td_pobox", length = 10)
	public String getTdPobox() {
		return this.tdPobox;
	}

	public void setTdPobox(String tdPobox) {
		con.check( "setTdPobox", tdPobox, true, 10);
		this.tdPobox = tdPobox;
	}

	@Column(name = "td_postal_code", length = 10)
	public String getTdPostalCode() {
		return this.tdPostalCode;
	}

	public void setTdPostalCode(String tdPostalCode) {
		con.check( "setTdPostalCode", tdPostalCode, true, 10);
		this.tdPostalCode = tdPostalCode;
	}

	@Column(name = "td_region", length = 12)
	public String getTdRegion() {
		return this.tdRegion;
	}

	public void setTdRegion(String tdRegion) {
		con.check( "setTdRegion", tdRegion, true, 12);
		this.tdRegion = tdRegion;
	}

	@Column(name = "county", length = 20)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		con.check( "setCounty", county, true, 20);
		this.county = county;
	}

	@Column(name = "township_name", length = 30)
	public String getTownshipName() {
		return this.townshipName;
	}

	public void setTownshipName(String townshipName) {
		con.check( "setTownshipName", townshipName, true, 30);
		this.townshipName = townshipName;
	}

	@Column(name = "subdivision", length = 20)
	public String getSubdivision() {
		return this.subdivision;
	}

	public void setSubdivision(String subdivision) {
		con.check( "setSubdivision", subdivision, true, 20);
		this.subdivision = subdivision;
	}

	@Column(name = "block", length = 6)
	public String getBlock() {
		return this.block;
	}

	public void setBlock(String block) {
		con.check( "setBlock", block, true, 6);
		this.block = block;
	}

	@Column(name = "lot", length = 6)
	public String getLot() {
		return this.lot;
	}

	public void setLot(String lot) {
		con.check( "setLot", lot, true, 6);
		this.lot = lot;
	}

	@Column(name = "time_zone", length = 15)
	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		con.check( "setTimeZone", timeZone, true, 15);
		this.timeZone = timeZone;
	}

	@Column(name = "coord_system", length = 512)
	public String getCoordSystem() {
		return this.coordSystem;
	}

	public void setCoordSystem(String coordSystem) {
		con.check( "setCoordSystem", coordSystem, true, 512);
		this.coordSystem = coordSystem;
	}	
	
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "address")
	public Set<AddressDistricts> getAddressDistrictses() {
		return this.addressDistrictses;
	}

	public void setAddressDistrictses(Set<AddressDistricts> addressDistrictses) {
		this.addressDistrictses = addressDistrictses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "address")
	public Set<AddressPositionPoints> getAddressPositionPointses() {
		return this.addressPositionPointses;
	}

	public void setAddressPositionPointses(
			Set<AddressPositionPoints> addressPositionPointses) {
		this.addressPositionPointses = addressPositionPointses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Organization> getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set<Organization> organizations) {
		this.organizations = organizations;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "address")
	public Set<ContactpersonAddresses> getContactpersonAddresseses() {
		return this.contactpersonAddresseses;
	}

	public void setContactpersonAddresseses(
			Set<ContactpersonAddresses> contactpersonAddresseses) {
		this.contactpersonAddresseses = contactpersonAddresseses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "address")
	public Set<AddressHazards> getAddressHazardses() {
		return this.addressHazardses;
	}

	public void setAddressHazardses(Set<AddressHazards> addressHazardses) {
		this.addressHazardses = addressHazardses;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "address")
	public Set<WorkOrder> getAddressWorkorders() {
		return this.addressWorkOrders;
	}

	public void setAddressWorkorders(Set<WorkOrder> addressWorkorders) {
		this.addressWorkOrders = addressWorkorders;
	}

}
