package com.sixthc.hbm;
// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddressHazards generated by hbm2java
 */
@Entity
@Table(name="address_hazards"
    ,catalog="wms"
)
public class AddressHazards  implements java.io.Serializable {


     private Integer id;
     private Hazards hazards;
     private Address address;

    public AddressHazards() {
    }

    public AddressHazards(Hazards hazards, Address address) {
       this.hazards = hazards;
       this.address = address;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hazard_id", nullable=false)
    public Hazards getHazards() {
        return this.hazards;
    }
    
    public void setHazards(Hazards hazards) {
        this.hazards = hazards;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="address_id", nullable=false)
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }




}


