package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment", catalog = "wms")
public class Attachment implements java.io.Serializable {
	private static Constraint con = new Constraint(Attachment.class);
	private static org.apache.log4j.Logger log = Logger
			.getLogger(Attachment.class);

	private Integer id;
	private String type;
	private String filename;
	private Set<WorkOrderAttachments> workOrderAttachmentses = new HashSet<WorkOrderAttachments>(
			0);

	public Attachment() {
	}

	public Attachment(String type, String filename) {
		this.type = type;
		this.filename = filename;
	}

	public Attachment(String type, String filename,
			Set<WorkOrderAttachments> workOrderAttachmentses) {
		this.type = type;
		this.filename = filename;
		this.workOrderAttachmentses = workOrderAttachmentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 12)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		con.check( "setType", type, false, 12);
		this.type = type;
	}

	@Column(name = "filename", nullable = false, length = 256)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		con.check( "setFilename", filename, false, 256);
		this.filename = filename;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "attachment")
	public Set<WorkOrderAttachments> getWorkOrderAttachmentses() {
		return this.workOrderAttachmentses;
	}

	public void setWorkOrderAttachmentses(
			Set<WorkOrderAttachments> workOrderAttachmentses) {
		this.workOrderAttachmentses = workOrderAttachmentses;
	}

}
