package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "wms")
public class Comment implements java.io.Serializable {
	private static Constraint con = new Constraint(Comment.class);
	private static org.apache.log4j.Logger log = Logger
			.getLogger(Comment.class);

	private Integer id;
	private String comment;
	private String commentType;
	private String commentSubtype;
	private Set<WorkOrderComments> workOrderCommentses = new HashSet<WorkOrderComments>(
			0);

	public Comment() {
	}

	public Comment(String comment) {
		this.comment = comment;
	}

	public Comment(String comment, String commentType, String commentSubtype,
			Set<WorkOrderComments> workOrderCommentses) {
		this.comment = comment;
		this.commentType = commentType;
		this.commentSubtype = commentSubtype;
		this.workOrderCommentses = workOrderCommentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@Column(name = "comment", nullable = false, length = 512)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		con.check( "setComment", comment, false, 512);
		this.comment = comment;
	}

	@Column(name = "comment_type", length = 12)
	public String getCommentType() {
		return this.commentType;
	}

	public void setCommentType(String commentType) {
		con.check( "setCommentType", commentType, true, 12);
		this.commentType = commentType;
	}

	@Column(name = "comment_subtype", length = 12)
	public String getCommentSubtype() {
		return this.commentSubtype;
	}

	public void setCommentSubtype(String commentSubtype) {
		con.check( "setCommentSubtype", commentSubtype, true, 12);
		this.commentSubtype = commentSubtype;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "comment")
	public Set<WorkOrderComments> getWorkOrderCommentses() {
		return this.workOrderCommentses;
	}

	public void setWorkOrderCommentses(
			Set<WorkOrderComments> workOrderCommentses) {
		this.workOrderCommentses = workOrderCommentses;
	}

}
