package com.sixthc.hbm;
// Generated May 31, 2015 2:36:12 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContactpersonPhones generated by hbm2java
 */
@Entity
@Table(name="contactperson_phones"
    
)
public class ContactpersonPhones  implements java.io.Serializable {


     private Integer id;
     private Phone phone;
     private Contactperson contactperson;

    public ContactpersonPhones() {
    }

    public ContactpersonPhones(Phone phone, Contactperson contactperson) {
       this.phone = phone;
       this.contactperson = contactperson;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="phone_id", nullable=false)
    public Phone getPhone() {
        return this.phone;
    }
    
    public void setPhone(Phone phone) {
        this.phone = phone;
    }
@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="contactperson_id", nullable=false)
    public Contactperson getContactperson() {
        return this.contactperson;
    }
    
    public void setContactperson(Contactperson contactperson) {
        this.contactperson = contactperson;
    }




}


