package com.sixthc.hbm;
// Generated May 25, 2015 9:14:25 AM by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContactpersonEmails generated by hbm2java
 */
@Entity
@Table(name="contactperson_emails"
    ,catalog="wms"
)
public class ContactpersonEmails  implements java.io.Serializable {


     private Integer id;
     private Email email;
     private Contactperson contactperson;

    public ContactpersonEmails() {
    }

    public ContactpersonEmails(Email email, Contactperson contactperson) {
       this.email = email;
       this.contactperson = contactperson;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="email_id", nullable=false)
    public Email getEmail() {
        return this.email;
    }
    
    public void setEmail(Email email) {
        this.email = email;
    }
@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="contactperson_id", nullable=false)
    public Contactperson getContactperson() {
        return this.contactperson;
    }
    
    public void setContactperson(Contactperson contactperson) {
        this.contactperson = contactperson;
    }




}


