package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "district", catalog = "wms")
public class District implements java.io.Serializable {
	private static Constraint con = new Constraint(Attachment.class);
	private static org.apache.log4j.Logger log = Logger
			.getLogger(District.class);

	private Integer id;
	private String type;
	private String name;
	private String code;
	private String description;
	private Set<AddressDistricts> addressDistrictses = new HashSet<AddressDistricts>(
			0);

	public District() {
	}

	public District(String name) {
		this.name = name;
	}

	public District(String type, String name, String code, String description,
			Set<AddressDistricts> addressDistrictses) {
		this.type = type;
		this.name = name;
		this.code = code;
		this.description = description;
		this.addressDistrictses = addressDistrictses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@Column(name = "type", length = 12)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		con.check( "setType", type, true, 12);
		this.type = type;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		con.check( "setName", name, false, 12);
		this.name = name;
	}

	@Column(name = "code", length = 12)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		con.check( "setCode", code, true, 12);
		this.code = code;
	}

	@Column(name = "description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		con.check( "setDescription", description, true, 512);
		this.description = description;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "district")
	public Set<AddressDistricts> getAddressDistrictses() {
		return this.addressDistrictses;
	}

	public void setAddressDistrictses(Set<AddressDistricts> addressDistrictses) {
		this.addressDistrictses = addressDistrictses;
	}
}
