package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email", catalog = "wms")
public class Email implements java.io.Serializable {
	private static Constraint con = new Constraint(Email.class);
	private static org.apache.log4j.Logger log = Logger.getLogger(Email.class);

	private Integer id;
	String email;
	private String emailType;
	private Integer priorityOrder;
	private Set<ContactpersonEmails> contactpersonEmailses = new HashSet<ContactpersonEmails>(
			0);

	public Email() {
	}

	public Email(String email) {
		this.email = email;
	}

	public Email(String email, String emailType, Integer priorityOrder,
			Set<ContactpersonEmails> contactpersonEmailses) {
		this.email = email;
		this.emailType = emailType;
		this.priorityOrder = priorityOrder;
		this.contactpersonEmailses = contactpersonEmailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		con.check( "setEmail", email, false, 30);
		this.email = email;
	}

	@Column(name = "email_type", length = 10)
	public String getEmailType() {
		return this.emailType;
	}

	public void setEmailType(String emailType) {
		con.check( "setEmailType", emailType, true, 10);
		this.emailType = emailType;
	}

	@Column(name = "priority_order")
	public Integer getPriorityOrder() {
		return this.priorityOrder;
	}

	public void setPriorityOrder(Integer priorityOrder) {
		this.priorityOrder = priorityOrder;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "email")
	public Set<ContactpersonEmails> getContactpersonEmailses() {
		return this.contactpersonEmailses;
	}

	public void setContactpersonEmailses(
			Set<ContactpersonEmails> contactpersonEmailses) {
		this.contactpersonEmailses = contactpersonEmailses;
	}

}
