package com.sixthc.hbm;
// Generated Jul 17, 2015 4:51:40 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MaintorderNames generated by hbm2java
 */
@Entity
@Table(name="maintorder_names"
    ,catalog="wms"
)
public class MaintorderNames  implements java.io.Serializable {


     private Integer id;
     private Nametype nametype;
     private Maintorder maintorder;
     private String name;

    public MaintorderNames() {
    }

	
    public MaintorderNames(Maintorder maintorder, String name) {
        this.maintorder = maintorder;
        this.name = name;
    }
    public MaintorderNames(Nametype nametype, Maintorder maintorder, String name) {
       this.nametype = nametype;
       this.maintorder = maintorder;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY,cascade = CascadeType.ALL)
    @JoinColumn(name="name_type_id")
    public Nametype getNametype() {
        return this.nametype;
    }
    
    public void setNametype(Nametype nametype) {
        this.nametype = nametype;
    }
@ManyToOne(fetch=FetchType.LAZY,cascade = CascadeType.ALL)
    @JoinColumn(name="maintorder_id", nullable=false)
    public Maintorder getMaintorder() {
        return this.maintorder;
    }
    
    public void setMaintorder(Maintorder maintorder) {
        this.maintorder = maintorder;
    }
    
    @Column(name="name", nullable=false, length=512)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


