package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * MaterialItemNames generated by hbm2java
 */
@Entity
@Table(name = "material_item_names", catalog = "wms")
public class MaterialItemNames implements java.io.Serializable {
	private static Constraint con = new Constraint(MaterialItemNames.class);

	private static org.apache.log4j.Logger log = Logger
			.getLogger(MaterialItemNames.class);

	private Integer id;
	private MaterialItem materialItem;
	private Nametype nametype;
	private String name;

	public MaterialItemNames() {
	}

	public MaterialItemNames(MaterialItem materialItem, String name) {
		this.materialItem = materialItem;
		this.name = name;
	}

	public MaterialItemNames(MaterialItem materialItem, Nametype nametype,
			String name) {
		this.materialItem = materialItem;
		this.nametype = nametype;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "material_item_id", nullable = false)
	public MaterialItem getMaterialItem() {
		return this.materialItem;
	}

	public void setMaterialItem(MaterialItem materialItem) {
		this.materialItem = materialItem;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "name_type_id")
	public Nametype getNametype() {
		return this.nametype;
	}

	public void setNametype(Nametype nametype) {
		this.nametype = nametype;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		con.check("setName", name, false, 40);
		this.name = name;
	}

}
