package com.sixthc.hbm;

// Generated Aug 7, 2016 8:49:30 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * MeterReading generated by hbm2java
 */
/**
 * @author BenGoodwin
 *
 */
@Entity
@Table(name = "meter_reading", catalog = "interop_dev")
public class MeterReading implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private MeterReadingSeq meterReadingSeq;
	private Date reportDate;
    private String reason;
	private String source;
	private String value;
	private Date timePeriodStart;
	private Date timePeriodEnd;
	private Set<MeterReadingQuality> meterReadingQualities = new HashSet<MeterReadingQuality>(
			0);

	public MeterReading() {
	}

	public MeterReading(MeterReadingSeq meterReadingSeq, Date reportDate,
			String source, String value, Date timePeriodStart,
			Date timePeriodEnd, Set<MeterReadingQuality> meterReadingQualities) {
		this.meterReadingSeq = meterReadingSeq;
		this.reportDate = reportDate;
		this.source = source;
		this.value = value;
		this.timePeriodStart = timePeriodStart;
		this.timePeriodEnd = timePeriodEnd;
		this.meterReadingQualities = meterReadingQualities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meter_reading_seq_id")
	public MeterReadingSeq getMeterReadingSeq() {
		return this.meterReadingSeq;
	}

	public void setMeterReadingSeq(MeterReadingSeq meterReadingSeq) {
		this.meterReadingSeq = meterReadingSeq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "report_date", length = 19)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "source", length = 512)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "value", precision = 22, scale = 0)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_period_start", length = 19)
	public Date getTimePeriodStart() {
		return this.timePeriodStart;
	}

	public void setTimePeriodStart(Date timePeriodStart) {
		this.timePeriodStart = timePeriodStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_period_end", length = 19)
	public Date getTimePeriodEnd() {
		return this.timePeriodEnd;
	}

	public void setTimePeriodEnd(Date timePeriodEnd) {
		this.timePeriodEnd = timePeriodEnd;
	}
	
    @Column(name="reason", length=512)	
	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "meterReading")
	public Set<MeterReadingQuality> getMeterReadingQualities() {
		return this.meterReadingQualities;
	}

	public void setMeterReadingQualities(
			Set<MeterReadingQuality> meterReadingQualities) {
		this.meterReadingQualities = meterReadingQualities;
	}

}
