package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * Objectref generated by hbm2java
 */
@Entity
@Table(name = "objectref", catalog = "wms")
public class Objectref implements java.io.Serializable {
	private static Constraint con = new Constraint(Objectref.class);

	private static org.apache.log4j.Logger log = Logger
			.getLogger(Objectref.class);

	private Integer id;
	private String primaryName;
	private String secondaryName;
	private String noun;
	private String objectGuid;
	private String utility;
	private String registeredName;
	private String systemName;
	private Set<WorkOrder> workOrders = new HashSet<WorkOrder>(0);
	private Set<WorkOrderLocationObjectRefs> workOrderLocationObjectRefses = new HashSet<WorkOrderLocationObjectRefs>(
			0);

	public Objectref() {
	}

	public Objectref(String primaryName) {
		this.primaryName = primaryName;
	}

	public Objectref(String primaryName, String secondaryName, String noun,
			String objectGuid, String utility, String registeredName,
			String systemName, Set<WorkOrder> workOrders,
			Set<WorkOrderLocationObjectRefs> workOrderLocationObjectRefses) {
		this.primaryName = primaryName;
		this.secondaryName = secondaryName;
		this.noun = noun;
		this.objectGuid = objectGuid;
		this.utility = utility;
		this.registeredName = registeredName;
		this.systemName = systemName;
		this.workOrders = workOrders;
		this.workOrderLocationObjectRefses = workOrderLocationObjectRefses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@Column(name = "primary_name", nullable = false, length = 40)
	public String getPrimaryName() {
		return this.primaryName;
	}

	public void setPrimaryName(String primaryName) {
		con.check( "setPrimaryName", primaryName, false, 40);
		this.primaryName = primaryName;
	}

	@Column(name = "secondary_name", length = 40)
	public String getSecondaryName() {
		return this.secondaryName;
	}

	public void setSecondaryName(String secondaryName) {
		con.check( "setSecondaryName", secondaryName, true, 40);
		this.secondaryName = secondaryName;
	}

	@Column(name = "noun", length = 12)
	public String getNoun() {
		return this.noun;
	}

	public void setNoun(String noun) {
		con.check( "setNoun", noun, true, 12);
		this.noun = noun;
	}

	@Column(name = "object_guid", length = 40)
	public String getObjectGuid() {
		return this.objectGuid;
	}

	public void setObjectGuid(String objectGuid) {
		con.check( "setObjectGUID", objectGuid, true, 40);
		this.objectGuid = objectGuid;
	}

	@Column(name = "utility", length = 12)
	public String getUtility() {
		return this.utility;
	}

	public void setUtility(String utility) {
		con.check( "setUtility", utility, true, 12);
		this.utility = utility;
	}

	@Column(name = "registered_name", length = 40)
	public String getRegisteredName() {
		return this.registeredName;
	}

	public void setRegisteredName(String registeredName) {
		con.check( "setRegisteredName", registeredName, true, 40);
		this.registeredName = registeredName;
	}

	@Column(name = "system_name", length = 40)
	public String getSystemName() {
		return this.systemName;
	}

	public void setSystemName(String systemName) {
		con.check( "setSystenName", systemName, true, 40);
		this.systemName = systemName;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "objectref")
	public Set<WorkOrder> getWorkOrders() {
		return this.workOrders;
	}

	public void setWorkOrders(Set<WorkOrder> workOrders) {
		this.workOrders = workOrders;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "objectref")
	public Set<WorkOrderLocationObjectRefs> getWorkOrderLocationObjectRefses() {
		return this.workOrderLocationObjectRefses;
	}

	public void setWorkOrderLocationObjectRefses(
			Set<WorkOrderLocationObjectRefs> workOrderLocationObjectRefses) {
		this.workOrderLocationObjectRefses = workOrderLocationObjectRefses;
	}

}
