package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name = "phone", catalog = "wms")
public class Phone implements java.io.Serializable {
	private static Constraint con = new Constraint(Phone.class);

	private static org.apache.log4j.Logger log = Logger.getLogger(Phone.class);

	private Integer id;
	private String areacode;
	private String citycode;
	private String countrycode;
	private String localnumber;
	private String extension;
	private String phonetype;
	private Integer priorityorder;
	private Set<ContactpersonPhones> contactpersonPhoneses = new HashSet<ContactpersonPhones>(
			0);
	private Set<Organization> organizations = new HashSet<Organization>(0);

	public Phone() {
	}

	public Phone(String areacode, String citycode, String countrycode,
			String localnumber, String extension, String phonetype,
			Integer priorityorder,
			Set<ContactpersonPhones> contactpersonPhoneses,
			Set<Organization> organizations) {
		this.areacode = areacode;
		this.citycode = citycode;
		this.countrycode = countrycode;
		this.localnumber = localnumber;
		this.extension = extension;
		this.phonetype = phonetype;
		this.priorityorder = priorityorder;
		this.contactpersonPhoneses = contactpersonPhoneses;
		this.organizations = organizations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@Column(name = "areacode", length = 5)
	public String getAreacode() {
		return this.areacode;
	}

	public void setAreacode(String areacode) {
		con.check( "setAreacode", areacode, true, 5);
		this.areacode = areacode;
	}

	@Column(name = "citycode", length = 5)
	public String getCitycode() {
		return this.citycode;
	}

	public void setCitycode(String citycode) {
		con.check( "setCitycode", citycode, true, 5);
		this.citycode = citycode;
	}

	@Column(name = "countrycode", length = 3)
	public String getCountrycode() {
		return this.countrycode;
	}

	public void setCountrycode(String countrycode) {
		con.check( "setCountrycode", countrycode, true, 3);
		this.countrycode = countrycode;
	}

	@Column(name = "localnumber", length = 10)
	public String getLocalnumber() {
		return this.localnumber;
	}

	public void setLocalnumber(String localnumber) {
		con.check( "setLocalNumber", localnumber, true, 10);
		this.localnumber = localnumber;
	}

	@Column(name = "extension")
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		con.check("setExtension", extension, true, 10);
		this.extension = extension;
	}

	@Column(name = "phonetype", length = 10)
	public String getPhonetype() {
		return this.phonetype;
	}

	public void setPhonetype(String phonetype) {
		con.check( "setPhoneType", phonetype, true, 10);
		this.phonetype = phonetype;
	}

	@Column(name = "priorityorder")
	public Integer getPriorityorder() {
		return this.priorityorder;
	}

	public void setPriorityorder(Integer priorityorder) {
		log.debug("setPiorityOrder : " + priorityorder);
		this.priorityorder = priorityorder;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "phone")
	public Set<ContactpersonPhones> getContactpersonPhoneses() {
		return this.contactpersonPhoneses;
	}

	public void setContactpersonPhoneses(
			Set<ContactpersonPhones> contactpersonPhoneses) {
		this.contactpersonPhoneses = contactpersonPhoneses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "phone")
	public Set<Organization> getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set<Organization> organizations) {
		this.organizations = organizations;
	}

}
