package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * Procedure generated by hbm2java
 */
@Entity
@Table(name = "proced", catalog = "wms")
public class Procedure implements java.io.Serializable {
	private static Constraint con = new Constraint(Procedure.class);

	private static org.apache.log4j.Logger log = Logger
			.getLogger(Procedure.class);

	private Integer id;
	private String instruction;
	private String kind;
	private Integer sequence;
	private Set<AssetProcedures> assetProcedureses = new HashSet<AssetProcedures>(
			0);
	private Set<ProcedureMeasurements> procedureMeasurementses = new HashSet<ProcedureMeasurements>(
			0);
	private Set<IdentifiedObjectProcedures> identifiedObjectProcedureses = new HashSet<IdentifiedObjectProcedures>(
			0);

	public Procedure() {
	}

	public Procedure(String instruction) {
		this.instruction = instruction;
	}

	public Procedure(String instruction, String kind, Integer sequence,
			Set<AssetProcedures> assetProcedureses,
			Set<ProcedureMeasurements> procedureMeasurementses,
			Set<IdentifiedObjectProcedures> identifiedObjectProcedureses) {
		this.instruction = instruction;
		this.kind = kind;
		this.sequence = sequence;
		this.assetProcedureses = assetProcedureses;
		this.procedureMeasurementses = procedureMeasurementses;
		this.identifiedObjectProcedureses = identifiedObjectProcedureses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@Column(name = "instruction", nullable = false, length = 512)
	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		con.check( "setInstruction", instruction, false, 512);
		this.instruction = instruction;
	}

	@Column(name = "kind", length = 20)
	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		con.check( "setKind", kind, true, 20);
		this.kind = kind;
	}

	@Column(name = "sequence")
	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "procedure")
	public Set<AssetProcedures> getAssetProcedureses() {
		return this.assetProcedureses;
	}

	public void setAssetProcedureses(Set<AssetProcedures> assetProcedureses) {
		this.assetProcedureses = assetProcedureses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "procedure")
	public Set<ProcedureMeasurements> getProcedureMeasurementses() {
		return this.procedureMeasurementses;
	}

	public void setProcedureMeasurementses(
			Set<ProcedureMeasurements> procedureMeasurementses) {
		this.procedureMeasurementses = procedureMeasurementses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "procedure")
	public Set<IdentifiedObjectProcedures> getIdentifiedObjectProcedureses() {
		return this.identifiedObjectProcedureses;
	}

	public void setIdentifiedObjectProcedureses(
			Set<IdentifiedObjectProcedures> identifiedObjectProcedureses) {
		this.identifiedObjectProcedureses = identifiedObjectProcedureses;
	}

}
