package com.sixthc.hbm;
// Generated Aug 4, 2016 8:48:46 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReadingTypeNames generated by hbm2java
 */
@Entity
@Table(name="reading_type_names"
    ,catalog="interop_dev"
)
public class ReadingTypeNames  implements java.io.Serializable {


     private Integer id;
     private ReadingType readingType;
     private Nametype nametype;
     private String name;

    public ReadingTypeNames() {
    }

    public ReadingTypeNames(ReadingType readingType, Nametype nametype, String name) {
       this.readingType = readingType;
       this.nametype = nametype;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="reading_type_id")
    public ReadingType getReadingType() {
        return this.readingType;
    }
    
    public void setReadingType(ReadingType readingType) {
        this.readingType = readingType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="name_type_id")
    public Nametype getNametype() {
        return this.nametype;
    }
    
    public void setNametype(Nametype nametype) {
        this.nametype = nametype;
    }
    
    @Column(name="name", length=512)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


