package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * Resultcode generated by hbm2java
 */
@Entity
@Table(name = "resultcode", catalog = "wms")
public class Resultcode implements java.io.Serializable {
	private static Constraint con = new Constraint(Resultcode.class);

	private static org.apache.log4j.Logger log = Logger
			.getLogger(Resultcode.class);

	private int id;
	private String name;

	public Resultcode() {
	}

	public Resultcode(int id) {
		this.id = id;
	}

	public Resultcode(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		con.check("setName", name, true, 20);
		this.name = name;
	}

}
