package com.sixthc.hbm;
// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SeqsId generated by hbm2java
 */
@Embeddable
public class SeqsId  implements java.io.Serializable {


     private String seqName;
     private Integer start;
     private Integer increment;
     private Integer curval;
     private Character flag;

    public SeqsId() {
    }

    public SeqsId(String seqName, Integer start, Integer increment, Integer curval, Character flag) {
       this.seqName = seqName;
       this.start = start;
       this.increment = increment;
       this.curval = curval;
       this.flag = flag;
    }
   

    @Column(name="seq_name", length=30)
    public String getSeqName() {
        return this.seqName;
    }
    
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    @Column(name="start")
    public Integer getStart() {
        return this.start;
    }
    
    public void setStart(Integer start) {
        this.start = start;
    }

    @Column(name="increment")
    public Integer getIncrement() {
        return this.increment;
    }
    
    public void setIncrement(Integer increment) {
        this.increment = increment;
    }

    @Column(name="curval")
    public Integer getCurval() {
        return this.curval;
    }
    
    public void setCurval(Integer curval) {
        this.curval = curval;
    }

    @Column(name="flag", length=1)
    public Character getFlag() {
        return this.flag;
    }
    
    public void setFlag(Character flag) {
        this.flag = flag;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeqsId) ) return false;
		 SeqsId castOther = ( SeqsId ) other; 
         
		 return ( (this.getSeqName()==castOther.getSeqName()) || ( this.getSeqName()!=null && castOther.getSeqName()!=null && this.getSeqName().equals(castOther.getSeqName()) ) )
 && ( (this.getStart()==castOther.getStart()) || ( this.getStart()!=null && castOther.getStart()!=null && this.getStart().equals(castOther.getStart()) ) )
 && ( (this.getIncrement()==castOther.getIncrement()) || ( this.getIncrement()!=null && castOther.getIncrement()!=null && this.getIncrement().equals(castOther.getIncrement()) ) )
 && ( (this.getCurval()==castOther.getCurval()) || ( this.getCurval()!=null && castOther.getCurval()!=null && this.getCurval().equals(castOther.getCurval()) ) )
 && ( (this.getFlag()==castOther.getFlag()) || ( this.getFlag()!=null && castOther.getFlag()!=null && this.getFlag().equals(castOther.getFlag()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSeqName() == null ? 0 : this.getSeqName().hashCode() );
         result = 37 * result + ( getStart() == null ? 0 : this.getStart().hashCode() );
         result = 37 * result + ( getIncrement() == null ? 0 : this.getIncrement().hashCode() );
         result = 37 * result + ( getCurval() == null ? 0 : this.getCurval().hashCode() );
         result = 37 * result + ( getFlag() == null ? 0 : this.getFlag().hashCode() );
         return result;
   }   


}


