package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.log4j.Logger;

/**
 * WorkTaskIdentifiedObjects generated by hbm2java
 */
@Entity
@Table(name = "work_task_identified_objects")
public class WorkTaskIdentifiedObjects implements java.io.Serializable {
	private static Constraint con = new Constraint(WorkTaskIdentifiedObjects.class);

	private static org.apache.log4j.Logger log = Logger
			.getLogger(WorkTaskIdentifiedObjects.class);

	private Integer id;
	private IdentifiedObject identifiedObject;
	private WorkTask workTask;
	private Date createdAt;
	private String createdBy;

	public WorkTaskIdentifiedObjects() {
	}

	public WorkTaskIdentifiedObjects(IdentifiedObject identifiedObject,
			WorkTask workTask, Date createdAt) {
		this.identifiedObject = identifiedObject;
		this.workTask = workTask;
		this.createdAt = createdAt;
	}

	public WorkTaskIdentifiedObjects(IdentifiedObject identifiedObject,
			WorkTask workTask, Date createdAt, String createdBy) {
		this.identifiedObject = identifiedObject;
		this.workTask = workTask;
		this.createdAt = createdAt;
		this.createdBy = createdBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "identified_object_id", nullable = false)
	public IdentifiedObject getIdentifiedObject() {
		return this.identifiedObject;
	}

	public void setIdentifiedObject(IdentifiedObject identifiedObject) {
		this.identifiedObject = identifiedObject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "work_task_id", nullable = false)
	public WorkTask getWorkTask() {
		return this.workTask;
	}

	public void setWorkTask(WorkTask workTask) {
		this.workTask = workTask;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		log.debug("setCreatedAt : " + createdAt);
		this.createdAt = createdAt;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		con.check("createdBy", createdBy, true, 20);
		this.createdBy = createdBy;
	}

}
