package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * WorkOrderHazards generated by hbm2java
 */
@Entity
@Table(name = "work_order_hazards", catalog = "wms")
public class WorkOrderHazards implements java.io.Serializable {
	private static org.apache.log4j.Logger log = Logger
			.getLogger(WorkOrderHazards.class);

	private Integer id;
	private WorkOrder workOrder;
	private Hazards hazards;

	public WorkOrderHazards() {
	}

	public WorkOrderHazards(WorkOrder workOrder, Hazards hazards) {
		this.workOrder = workOrder;
		this.hazards = hazards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "work_order_id", nullable = false)
	public WorkOrder getWorkOrder() {
		return this.workOrder;
	}

	public void setWorkOrder(WorkOrder workOrder) {
		this.workOrder = workOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "hazard_id", nullable = false)
	public Hazards getHazards() {
		return this.hazards;
	}

	public void setHazards(Hazards hazards) {
		this.hazards = hazards;
	}

}
