package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.log4j.Logger;

/**
 * Workorderimage generated by hbm2java
 */
@Entity
@Table(name = "workorderimage", catalog = "wms")
public class Workorderimage implements java.io.Serializable {
	private static Constraint con = new Constraint(Workorderimage.class);

	private static org.apache.log4j.Logger log = Logger
			.getLogger(Workorderimage.class);

	private Integer id;
	private Date createDate;
	private Integer workorderId;
	private String url;
	private String error;
	private String filename;
	private String comment;
	private String description;

	public Workorderimage() {
	}

	public Workorderimage(Date createDate) {
		this.createDate = createDate;
	}

	public Workorderimage(Date createDate, Integer workorderId, String url,
			String error, String filename) {
		this.createDate = createDate;
		this.workorderId = workorderId;
		this.url = url;
		this.error = error;
		this.filename = filename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		log.debug("setCreateDate : " + createDate);
		this.createDate = createDate;
	}

	@Column(name = "workorder_id")
	public Integer getWorkorderId() {
		return this.workorderId;
	}

	public void setWorkorderId(Integer workorderId) {
		this.workorderId = workorderId;
	}

	@Column(name = "url", length = 800)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		con.check( "setURL", url, true, 800);
		this.url = url;
	}

	@Column(name = "error", length = 256)
	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		con.check( "setError", error, true, 256);
		this.error = error;
	}

	@Column(name = "filename", length = 1025)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		con.check( "setFilename", filename, true, 1025);
		this.filename = filename;
	}

	@Column(name="comment", length=512)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name="description", length=512)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	

}
