package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.log4j.Logger;

/**
 * WorkTask generated by hbm2java
 */
@Entity
@Table(name = "work_task", catalog = "wms")
public class WorkTask implements java.io.Serializable {
	private static Constraint con = new Constraint(WorkTask.class);

	private static org.apache.log4j.Logger log = Logger
			.getLogger(WorkTask.class);

	private Integer id;
	private Asset asset;
	private String mrid;
	private String instructions;
	private String subject;
	private Date crewEta;
	private String taskType;
	private Set<WorkTaskAssets> workTaskAssetses = new HashSet<WorkTaskAssets>(
			0);
	private Set<WorkTaskOldAssets> workTaskOldAssetses = new HashSet<WorkTaskOldAssets>(
			0);
	private Set<WorkOrderWorkTasks> workOrderWorkTaskses = new HashSet<WorkOrderWorkTasks>(
			0);
	private Set<WorkTaskMaterialItems> workTaskMaterialItemses = new HashSet<WorkTaskMaterialItems>(
			0);
	private Set<WorkTaskTimeSchedules> workTaskTimeScheduleses = new HashSet<WorkTaskTimeSchedules>(
			0);
	private Set<WorkTaskIdentifiedObjects> workTaskIdentifiedObjectses = new HashSet<WorkTaskIdentifiedObjects>(
			0);
	private Set<WorkTaskCrews> workTaskCrewses = new HashSet<WorkTaskCrews>(0);
	private Set<WorkTaskNames> workTaskNameses = new HashSet<WorkTaskNames>(0);

	public WorkTask() {
	}

	public WorkTask(String mrid, String subject) {
		this.mrid = mrid;
		this.subject = subject;
	}

	public WorkTask(Asset asset, String mrid, String instructions,
			String subject, Date crewEta, String taskType,
			Set<WorkTaskAssets> workTaskAssetses,
			Set<WorkOrderWorkTasks> workOrderWorkTaskses,
			Set<WorkTaskMaterialItems> workTaskMaterialItemses,
			Set<WorkTaskTimeSchedules> workTaskTimeScheduleses,
			Set<WorkTaskIdentifiedObjects> workTaskIdentifiedObjectses,
			Set<WorkTaskCrews> workTaskCrewses,
			Set<WorkTaskNames> workTaskNameses) {
		this.asset = asset;
		this.mrid = mrid;
		this.instructions = instructions;
		this.subject = subject;
		this.crewEta = crewEta;
		this.taskType = taskType;
		this.workTaskAssetses = workTaskAssetses;
		this.workOrderWorkTaskses = workOrderWorkTaskses;
		this.workTaskMaterialItemses = workTaskMaterialItemses;
		this.workTaskTimeScheduleses = workTaskTimeScheduleses;
		this.workTaskIdentifiedObjectses = workTaskIdentifiedObjectses;
		this.workTaskCrewses = workTaskCrewses;
		this.workTaskNameses = workTaskNameses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "old_asset_id")
	public Asset getAsset() {
		return this.asset;
	}

	public void setAsset(Asset asset) {
		this.asset = asset;
	}

	@Column(name = "mRID", nullable = false, length = 20)
	public String getMrid() {
		return this.mrid;
	}

	public void setMrid(String mrid) {
		con.check( "setMrid", mrid, false, 20);
		this.mrid = mrid;
	}

	@Column(name = "instructions", length = 1024)
	public String getInstructions() {
		return this.instructions;
	}

	public void setInstructions(String instructions) {
		con.check( "setInstructions", instructions, true, 1024);
		this.instructions = instructions;
	}

	@Column(name = "subject", nullable = false, length = 20)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		con.check( "setSubject", subject, false, 20);
		this.subject = subject;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crew_eta", length = 19)
	public Date getCrewEta() {
		return this.crewEta;
	}

	public void setCrewEta(Date crewEta) {
		log.debug("setCrewEta : " + crewEta);
		this.crewEta = crewEta;
	}

	@Column(name = "task_type", length = 12)
	public String getTaskType() {
		return this.taskType;
	}

	public void setTaskType(String taskType) {
		con.check( "setTaskType", taskType, true, 12);
		this.taskType = taskType;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTask")
	public Set<WorkTaskAssets> getWorkTaskAssetses() {
		return this.workTaskAssetses;
	}

	public void setWorkTaskAssetses(Set<WorkTaskAssets> workTaskAssetses) {
		this.workTaskAssetses = workTaskAssetses;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTask")
	public Set<WorkTaskOldAssets> getWorkTaskOldAssetses() {
		return this.workTaskOldAssetses;
	}

	public void setWorkTaskOldAssetses(Set<WorkTaskOldAssets> workTaskOldAssetses) {
		this.workTaskOldAssetses = workTaskOldAssetses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTask")
	public Set<WorkOrderWorkTasks> getWorkOrderWorkTaskses() {
		return this.workOrderWorkTaskses;
	}

	public void setWorkOrderWorkTaskses(
			Set<WorkOrderWorkTasks> workOrderWorkTaskses) {
		this.workOrderWorkTaskses = workOrderWorkTaskses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTask")
	public Set<WorkTaskMaterialItems> getWorkTaskMaterialItemses() {
		return this.workTaskMaterialItemses;
	}

	public void setWorkTaskMaterialItemses(
			Set<WorkTaskMaterialItems> workTaskMaterialItemses) {
		this.workTaskMaterialItemses = workTaskMaterialItemses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTask")
	public Set<WorkTaskTimeSchedules> getWorkTaskTimeScheduleses() {
		return this.workTaskTimeScheduleses;
	}

	public void setWorkTaskTimeScheduleses(
			Set<WorkTaskTimeSchedules> workTaskTimeScheduleses) {
		this.workTaskTimeScheduleses = workTaskTimeScheduleses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTask")
	public Set<WorkTaskIdentifiedObjects> getWorkTaskIdentifiedObjectses() {
		return this.workTaskIdentifiedObjectses;
	}

	public void setWorkTaskIdentifiedObjectses(
			Set<WorkTaskIdentifiedObjects> workTaskIdentifiedObjectses) {
		this.workTaskIdentifiedObjectses = workTaskIdentifiedObjectses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTask")
	public Set<WorkTaskCrews> getWorkTaskCrewses() {
		return this.workTaskCrewses;
	}

	public void setWorkTaskCrewses(Set<WorkTaskCrews> workTaskCrewses) {
		this.workTaskCrewses = workTaskCrewses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTask")
	public Set<WorkTaskNames> getWorkTaskNameses() {
		return this.workTaskNameses;
	}

	public void setWorkTaskNameses(Set<WorkTaskNames> workTaskNameses) {
		this.workTaskNameses = workTaskNameses;
	}

}
