
package com.sixthc.server.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExecuteMaintOrderCreateService", targetNamespace = "http://ws.server.sixthc.com/", wsdlLocation = "http://localhost:8080/epri-61968-6/MaintOrderCreate?wsdl")
public class ExecuteMaintOrderCreateService
    extends Service
{

    private final static URL EXECUTEMAINTORDERCREATESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXECUTEMAINTORDERCREATESERVICE_EXCEPTION;
    private final static QName EXECUTEMAINTORDERCREATESERVICE_QNAME = new QName("http://ws.server.sixthc.com/", "ExecuteMaintOrderCreateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/epri-61968-6/MaintOrderCreate?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXECUTEMAINTORDERCREATESERVICE_WSDL_LOCATION = url;
        EXECUTEMAINTORDERCREATESERVICE_EXCEPTION = e;
    }

    public ExecuteMaintOrderCreateService() {
        super(__getWsdlLocation(), EXECUTEMAINTORDERCREATESERVICE_QNAME);
    }

    public ExecuteMaintOrderCreateService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXECUTEMAINTORDERCREATESERVICE_QNAME, features);
    }

    public ExecuteMaintOrderCreateService(URL wsdlLocation) {
        super(wsdlLocation, EXECUTEMAINTORDERCREATESERVICE_QNAME);
    }

    public ExecuteMaintOrderCreateService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXECUTEMAINTORDERCREATESERVICE_QNAME, features);
    }

    public ExecuteMaintOrderCreateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExecuteMaintOrderCreateService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MaintenanceOrdersPort
     */
    @WebEndpoint(name = "ExecuteMaintOrderCreatePort")
    public MaintenanceOrdersPort getExecuteMaintOrderCreatePort() {
        return super.getPort(new QName("http://ws.server.sixthc.com/", "ExecuteMaintOrderCreatePort"), MaintenanceOrdersPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MaintenanceOrdersPort
     */
    @WebEndpoint(name = "ExecuteMaintOrderCreatePort")
    public MaintenanceOrdersPort getExecuteMaintOrderCreatePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.server.sixthc.com/", "ExecuteMaintOrderCreatePort"), MaintenanceOrdersPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXECUTEMAINTORDERCREATESERVICE_EXCEPTION!= null) {
            throw EXECUTEMAINTORDERCREATESERVICE_EXCEPTION;
        }
        return EXECUTEMAINTORDERCREATESERVICE_WSDL_LOCATION;
    }

}
