delete from address;
delete from address_districts;
delete from address_hazards;
delete from address_position_points;
delete from asset;
delete from asset_names;
delete from asset_proceds;
delete from attachment;
delete from comment;
delete from contactperson;
delete from contactperson_addresses;
delete from contactperson_emails;
delete from contactperson_other_contactinfos;
delete from contactperson_phones;
delete from crew;
delete from crew_assets;
delete from crew_names;
delete from district;
delete from email;
# delete from eprilog;
delete from hazards;
delete from identified_object;
delete from identified_object_hazards;
delete from identified_object_names;
delete from identified_object_position_points;
delete from identified_object_procedures;
# delete from interface;
delete from material_item;
delete from material_item_names;
delete from measurement;
delete from name_type_authority;
delete from nametype;
delete from objectref;
delete from organization;
delete from organization_names;
delete from other_contactinfo;
# delete from package;
# delete from packages_vendor_role_types;
delete from phone;
# delete from procedure;
delete from procedure_measurements;
# delete from proxy_interface;
# delete from request;
delete from resultcode;
delete from seqs;
delete from time_schedule;
# delete from vendor_role;
# delete from vendor_role_type;
delete from work_order;
delete from work_order_attachments;
delete from work_order_comments;
delete from work_order_hazards;
delete from work_order_location_object_refs;
delete from work_order_names;
delete from work_order_schedules;
delete from work_order_work_tasks;
delete from work_position_points;
delete from work_task;
delete from work_task_assets;
delete from work_task_old_assets;
delete from work_task_crews;
delete from work_task_identified_objects;
delete from work_task_material_items;
delete from work_task_names;
delete from work_task_time_schedules;
delete from workorderimage          ;
delete from work_order_organizations;
delete from eprilog;
delete from crew_contactpersons;
delete from maintorder;
delete from maintorder_names;
