
package com.sixthc.server.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetMaintOrderService", targetNamespace = "http://ws.server.sixthc.com/", wsdlLocation = "http://localhost:8080/epriConnect/MaintOrderServiceGet?wsdl")
public class GetMaintOrderService
    extends Service
{

    private final static URL GETMAINTORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETMAINTORDERSERVICE_EXCEPTION;
    private final static QName GETMAINTORDERSERVICE_QNAME = new QName("http://ws.server.sixthc.com/", "GetMaintOrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/epriConnect/MaintOrderServiceGet?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETMAINTORDERSERVICE_WSDL_LOCATION = url;
        GETMAINTORDERSERVICE_EXCEPTION = e;
    }

    public GetMaintOrderService() {
        super(__getWsdlLocation(), GETMAINTORDERSERVICE_QNAME);
    }

    public GetMaintOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETMAINTORDERSERVICE_QNAME, features);
    }

    public GetMaintOrderService(URL wsdlLocation) {
        super(wsdlLocation, GETMAINTORDERSERVICE_QNAME);
    }

    public GetMaintOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETMAINTORDERSERVICE_QNAME, features);
    }

    public GetMaintOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetMaintOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetMaintenanceOrdersPort
     */
    @WebEndpoint(name = "GetMaintOrderPort")
    public GetMaintenanceOrdersPort getGetMaintOrderPort() {
        return super.getPort(new QName("http://ws.server.sixthc.com/", "GetMaintOrderPort"), GetMaintenanceOrdersPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetMaintenanceOrdersPort
     */
    @WebEndpoint(name = "GetMaintOrderPort")
    public GetMaintenanceOrdersPort getGetMaintOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.server.sixthc.com/", "GetMaintOrderPort"), GetMaintenanceOrdersPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETMAINTORDERSERVICE_EXCEPTION!= null) {
            throw GETMAINTORDERSERVICE_EXCEPTION;
        }
        return GETMAINTORDERSERVICE_WSDL_LOCATION;
    }

}
