<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://iec.ch/TC57/2015/ExecuteServiceOrdersOperationSet" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:infoMessage="http://iec.ch/TC57/2015/ServiceOrdersOperationSetMessage" xmlns:ns="http://iec.ch/TC57/2011/schema/message" xmlns:ns1="http://iec.ch/TC57/2015/ServiceOrders#" name="ExecuteServiceOrdersOperationSet" targetNamespace="http://iec.ch/TC57/2015/ExecuteServiceOrdersOperationSet">
	<wsdl:types>
		<xs:schema targetNamespace="http://iec.ch/TC57/2015/ExecuteServiceOrdersOperationSet" elementFormDefault="qualified">
			<xs:import namespace="http://iec.ch/TC57/2015/ServiceOrdersOperationSetMessage" schemaLocation="xsd/ServiceOrdersOperationSetMessage.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="ExecuteServiceOrdersOperationSetRequestMessage">
		<wsdl:part name="ExecuteServiceOrdersOperationSetRequestMessage" element="infoMessage:ExecuteServiceOrdersOperationSet"/>
	</wsdl:message>
	<wsdl:message name="ResponseMessage">
		<wsdl:part name="ResponseMessage" element="infoMessage:ServiceOrdersOperationSetResponseMessage"/>
	</wsdl:message>
	<wsdl:message name="FaultMessage">
		<wsdl:part name="FaultMessage" element="infoMessage:ServiceOrdersOperationSetFaultMessage"/>
	</wsdl:message>
	<wsdl:portType name="ServiceOrdersOperationSet_Port">
		<wsdl:operation name="ExecuteServiceOrdersOperationSet">
			<wsdl:input name="ExecuteServiceOrdersOperationSetRequest" message="tns:ExecuteServiceOrdersOperationSetRequestMessage"/>
			<wsdl:output name="ExecuteServiceOrdersOperationSetResponse" message="tns:ResponseMessage"/>
			<wsdl:fault name="ExecuteServiceOrdersOperationSetFault" message="tns:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ServiceOrdersOperationSet_Binding" type="tns:ServiceOrdersOperationSet_Port">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ExecuteServiceOrdersOperationSet">
			<soap:operation soapAction="http://iec.ch/TC57/2015/ServiceOrdersOperationSet/ExecuteServiceOrdersOperationSet" style="document"/>
			<wsdl:input name="ExecuteServiceOrdersOperationSetRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="ExecuteServiceOrdersOperationSetResponse">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="ExecuteServiceOrdersOperationSetFault">
				<soap:fault name="ExecuteServiceOrdersOperationSetFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ExecuteServiceOrdersOperationSet">
		<wsdl:port name="ServiceOrdersOperationSet_Port" binding="tns:ServiceOrdersOperationSet_Binding">
			<soap:address location="http://iec.ch/TC57/2015/ExecuteServiceOrdersOperationSet"/>
		</wsdl:port>
	</wsdl:service>
	<xs:schema targetNamespace="http://iec.ch/TC57/2015/ExecuteServiceOrdersOperationSetMessage" elementFormDefault="qualified">
		<xs:import namespace="http://iec.ch/TC57/2015/ServiceOrdersOperationSetMessage" schemaLocation="xsd/ServiceOrdersOperationSetMessage.xsd"/>
		<!--<xs:include schemaLocation="xsd/ServiceOrdersMessage.xsd"/>-->
	</xs:schema>
	<!-- Message Definitions -->
	<!-- Port Definitions -->
</wsdl:definitions>
