package ch.iec.tc57._2011.meterservicerequests;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2015-07-20T15:46:14.376-04:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "GetMeterServiceRequests", 
                  wsdlLocation = "file:/Users/BenGoodwin/git/opentemp2/openwms/61968/wsdl/GetMeterServiceRequests.wsdl",
                  targetNamespace = "http://iec.ch/TC57/2011/MeterServiceRequests") 
public class GetMeterServiceRequests extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://iec.ch/TC57/2011/MeterServiceRequests", "GetMeterServiceRequests");
    public final static QName GetMeterServiceRequestsPort = new QName("http://iec.ch/TC57/2011/MeterServiceRequests", "GetMeterServiceRequests_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/BenGoodwin/git/opentemp2/openwms/61968/wsdl/GetMeterServiceRequests.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetMeterServiceRequests.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/BenGoodwin/git/opentemp2/openwms/61968/wsdl/GetMeterServiceRequests.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetMeterServiceRequests(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetMeterServiceRequests(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetMeterServiceRequests() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetMeterServiceRequests(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetMeterServiceRequests(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetMeterServiceRequests(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GetMeterServiceRequestsPort
     */
    @WebEndpoint(name = "GetMeterServiceRequests_Port")
    public GetMeterServiceRequestsPort getGetMeterServiceRequestsPort() {
        return super.getPort(GetMeterServiceRequestsPort, GetMeterServiceRequestsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetMeterServiceRequestsPort
     */
    @WebEndpoint(name = "GetMeterServiceRequests_Port")
    public GetMeterServiceRequestsPort getGetMeterServiceRequestsPort(WebServiceFeature... features) {
        return super.getPort(GetMeterServiceRequestsPort, GetMeterServiceRequestsPort.class, features);
    }

}
