
package com.sixthc.server.ws;

import javax.xml.ws.WebFault;
import ch.iec.tc57._2015.serviceordersmessage.ServiceOrdersFaultMessageType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServiceOrdersFaultMessage", targetNamespace = "http://iec.ch/TC57/2015/ServiceOrdersMessage")
public class FaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceOrdersFaultMessageType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FaultMessage(String message, ServiceOrdersFaultMessageType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FaultMessage(String message, ServiceOrdersFaultMessageType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ch.iec.tc57._2015.serviceordersmessage.ServiceOrdersFaultMessageType
     */
    public ServiceOrdersFaultMessageType getFaultInfo() {
        return faultInfo;
    }

}
