package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * ContactpersonCrews generated by hbm2java
 */
@Entity
@Table(name = "crew_contactpersons")
public class CrewContactpersons implements java.io.Serializable {
	private static org.apache.log4j.Logger log = Logger
			.getLogger(CrewContactpersons.class);

	private Integer id;
	private Crew crew;
	private Contactperson contactPerson;

	public CrewContactpersons() {
	}

	public CrewContactpersons(Crew crew, Contactperson Contactperson) {
		this.crew = crew;
		this.contactPerson = Contactperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "crew_id", nullable = false)
	public Crew getCrew() {
		return this.crew;
	}

	public void setCrew(Crew crew) {
		this.crew = crew;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "contact_person_id", nullable = false)
	public Contactperson getContactperson() {
		return this.contactPerson;
	}

	public void setContactperson(Contactperson Contactperson) {
		this.contactPerson = Contactperson;
	}

}
