package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * IdentifiedObjectNames generated by hbm2java
 */
@Entity
@Table(name = "identified_object_names")
public class IdentifiedObjectNames implements java.io.Serializable {
	private static Constraint con = new Constraint(IdentifiedObjectNames.class);

	private static org.apache.log4j.Logger log = Logger
			.getLogger(IdentifiedObjectNames.class);

	private Integer id;
	private IdentifiedObject identifiedObject;
	private Nametype nametype;
	private String name;

	public IdentifiedObjectNames() {
	}

	public IdentifiedObjectNames(IdentifiedObject identifiedObject, String name) {
		this.identifiedObject = identifiedObject;
		this.name = name;
	}

	public IdentifiedObjectNames(IdentifiedObject identifiedObject,
			Nametype nametype, String name) {
		this.identifiedObject = identifiedObject;
		this.nametype = nametype;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "identified_object_id", nullable = false)
	public IdentifiedObject getIdentifiedObject() {
		return this.identifiedObject;
	}

	public void setIdentifiedObject(IdentifiedObject identifiedObject) {
		this.identifiedObject = identifiedObject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "name_type_id")
	public Nametype getNametype() {
		return this.nametype;
	}

	public void setNametype(Nametype nametype) {
		this.nametype = nametype;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		con.check( "setName", name, false, 40);
		this.name = name;
	}

}
