package com.sixthc.hbm;
// Generated Aug 6, 2016 4:08:56 PM by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MeterMultiplier generated by hbm2java
 */
@Entity
@Table(name="meter_multiplier"
    ,catalog="interop_dev"
)
public class MeterMultiplier  implements java.io.Serializable {


     private int id;
     private Asset asset;
     private String mrid;
     private String kind;
     private Double value;
     private Set<MeterMultiplierNames> meterMultiplierNameses = new HashSet<MeterMultiplierNames>(0);

    public MeterMultiplier() {
    }

	
    public MeterMultiplier(int id) {
        this.id = id;
    }
    public MeterMultiplier(int id, Asset asset, String mrid, String kind, Double value, Set<MeterMultiplierNames> meterMultiplierNameses) {
       this.id = id;
       this.asset = asset;
       this.mrid = mrid;
       this.kind = kind;
       this.value = value;
       this.meterMultiplierNameses = meterMultiplierNameses;
    }
   
 	@Id
 	@GeneratedValue(strategy = IDENTITY)
 	@Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="asset_id")
    public Asset getAsset() {
        return this.asset;
    }
    
    public void setAsset(Asset asset) {
        this.asset = asset;
    }
    
    @Column(name="mrid", length=512)
    public String getMrid() {
        return this.mrid;
    }
    
    public void setMrid(String mrid) {
        this.mrid = mrid;
    }
    
    @Column(name="kind", length=512)
    public String getKind() {
        return this.kind;
    }
    
    public void setKind(String kind) {
        this.kind = kind;
    }
    
    @Column(name="value", precision=22, scale=0)
    public Double getValue() {
        return this.value;
    }
    
    public void setValue(Double value) {
        this.value = value;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="meterMultiplier")
    public Set<MeterMultiplierNames> getMeterMultiplierNameses() {
        return this.meterMultiplierNameses;
    }
    
    public void setMeterMultiplierNameses(Set<MeterMultiplierNames> meterMultiplierNameses) {
        this.meterMultiplierNameses = meterMultiplierNameses;
    }




}


