package com.sixthc.hbm;
// Generated Aug 6, 2016 4:08:56 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MeterMultiplierNames generated by hbm2java
 */
@Entity
@Table(name="meter_multiplier_names"
    ,catalog="interop_dev"
)
public class MeterMultiplierNames  implements java.io.Serializable {


     private Integer id;
     private MeterMultiplier meterMultiplier;
     private Nametype nametype;
     private String name;

    public MeterMultiplierNames() {
    }

	
    public MeterMultiplierNames(MeterMultiplier meterMultiplier, String name) {
        this.meterMultiplier = meterMultiplier;
        this.name = name;
    }
    public MeterMultiplierNames(MeterMultiplier meterMultiplier, Nametype nametype, String name) {
       this.meterMultiplier = meterMultiplier;
       this.nametype = nametype;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="meter_multiplier_id", nullable=false)
    public MeterMultiplier getMeterMultiplier() {
        return this.meterMultiplier;
    }
    
    public void setMeterMultiplier(MeterMultiplier meterMultiplier) {
        this.meterMultiplier = meterMultiplier;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="name_type_id")
    public Nametype getNametype() {
        return this.nametype;
    }
    
    public void setNametype(Nametype nametype) {
        this.nametype = nametype;
    }
    
    @Column(name="name", nullable=false, length=512)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


