package com.sixthc.hbm;
// Generated Aug 7, 2016 8:49:30 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * MeterReadingQuality generated by hbm2java
 */
@Entity
@Table(name="meter_reading_quality"
    ,catalog="interop_dev"
)
public class MeterReadingQuality  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private MeterReading meterReading;
     private String comment;
     private String source;
     private String qualityType;

    public MeterReadingQuality() {
    }

    public MeterReadingQuality(MeterReading meterReading, String comment, String source, String qualityType) {
       this.meterReading = meterReading;
       this.comment = comment;
       this.source = source;
       this.qualityType = qualityType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="timestamp", length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="meter_reading_id")
    public MeterReading getMeterReading() {
        return this.meterReading;
    }
    
    public void setMeterReading(MeterReading meterReading) {
        this.meterReading = meterReading;
    }
    
    @Column(name="comment", length=512)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    
    @Column(name="source", length=512)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    
    @Column(name="quality_type", length=512)
    public String getQualityType() {
        return this.qualityType;
    }
    
    public void setQualityType(String qualityType) {
        this.qualityType = qualityType;
    }




}


