package com.sixthc.hbm;

// Generated Jun 3, 2015 2:34:41 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * OrganizationNames generated by hbm2java
 */
@Entity
@Table(name = "organization_names")
public class OrganizationNames implements java.io.Serializable {
	private static Constraint con = new Constraint(OrganizationNames.class);

	private static org.apache.log4j.Logger log = Logger
			.getLogger(OrganizationNames.class);

	private Integer id;
	private Nametype nametype;
	private Organization organization;
	private String name;

	public OrganizationNames() {
	}
	


	public OrganizationNames(Nametype nametype, Organization organization,
			String name) {
		this.nametype = nametype;
		this.organization = organization;
		this.name = name;
	}
	
	public OrganizationNames(Organization organization,
			String name) {
		this.organization = organization;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		log.debug("setId : " + id);
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "name_type_id", nullable = false)
	public Nametype getNametype() {
		return this.nametype;
	}

	public void setNametype(Nametype nametype) {
		this.nametype = nametype;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "organization_id", nullable = false)
	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		con.check("setName", name, false, 20);
		this.name = name;
	}

}
