package com.sixthc.hbm;
// Generated Jul 31, 2016 11:33:17 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReadingQualityTypeNames generated by hbm2java
 */
@Entity
@Table(name="reading_quality_type_names"
    ,catalog="interop_dev"
)
public class ReadingQualityTypeNames  implements java.io.Serializable {


     private Integer id;
     private ReadingQualityType readingQualityType;
     private Nametype nametype;
     private String name;

    public ReadingQualityTypeNames() {
    }

    public ReadingQualityTypeNames(ReadingQualityType readingQualityType, Nametype nametype, String name) {
       this.readingQualityType = readingQualityType;
       this.nametype = nametype;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="reading_quality_type_id")
    public ReadingQualityType getReadingQualityType() {
        return this.readingQualityType;
    }
    
    public void setReadingQualityType(ReadingQualityType readingQualityType) {
        this.readingQualityType = readingQualityType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="name_type_id")
    public Nametype getNametype() {
        return this.nametype;
    }
    
    public void setNametype(Nametype nametype) {
        this.nametype = nametype;
    }
    
    @Column(name="name", length=512)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


