package com.sixthc.hbm;
// Generated Jul 31, 2016 11:33:17 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ReadingQualityType generated by hbm2java
 */
@Entity
@Table(name="reading_quality_type"
    ,catalog="interop_dev"
)
public class ReadingQualityType  implements java.io.Serializable {


     private int id;
     private Maintorder maintorder;
     private String mrid;
     private String category;
     private String subCategory;
     private String systemId;
     private Set<ReadingQualityTypeNames> readingQualityTypeNameses = new HashSet<ReadingQualityTypeNames>(0);

    public ReadingQualityType() {
    }

	
    public ReadingQualityType(int id) {
        this.id = id;
    }
    public ReadingQualityType(int id, Maintorder maintorder, String mrid, String category, String subCategory, String systemId, Set<ReadingQualityTypeNames> readingQualityTypeNameses) {
       this.id = id;
       this.maintorder = maintorder;
       this.mrid = mrid;
       this.category = category;
       this.subCategory = subCategory;
       this.systemId = systemId;
       this.readingQualityTypeNameses = readingQualityTypeNameses;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maint_order_id")
    public Maintorder getMaintorder() {
        return this.maintorder;
    }
    
    public void setMaintorder(Maintorder maintorder) {
        this.maintorder = maintorder;
    }
    
    @Column(name="mrid", length=512)
    public String getMrid() {
        return this.mrid;
    }
    
    public void setMrid(String mrid) {
        this.mrid = mrid;
    }
    
    @Column(name="category", length=512)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    
    @Column(name="sub_category", length=512)
    public String getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory;
    }
    
    @Column(name="system_id", length=512)
    public String getSystemId() {
        return this.systemId;
    }
    
    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="readingQualityType")
    public Set<ReadingQualityTypeNames> getReadingQualityTypeNameses() {
        return this.readingQualityTypeNameses;
    }
    
    public void setReadingQualityTypeNameses(Set<ReadingQualityTypeNames> readingQualityTypeNameses) {
        this.readingQualityTypeNameses = readingQualityTypeNameses;
    }




}


